# Generated by Django 2.2.6 on 2019-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.IntegerField()),
                ('prating', models.IntegerField(default=0)),
                ('pshort_description', models.CharField(default='', max_length=300)),
                ('plong_description', models.CharField(default='', max_length=2000)),
                ('pavailability', models.CharField(max_length=100)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('pmaterial', models.ManyToManyField(to='product.Material')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
